#!/usr/bin/env bash
#
# Generates the committed kit content from the hand-edited shared/ tree.
#
# shared/ is the single source of truth for the orchestrator role, the
# sub-agents, the rules and the skills. This script is a pure function from
# shared/ to the subtrees of agent/files/home it owns (OWNED below); everything
# else in the kit is hand-owned and never read or written.
#
# Sources use a flat YAML frontmatter subset: `key: value` lines only, no
# nesting, no block scalars, keys from an allowlist. Anything else is rejected
# rather than guessed at. Bodies are copied with tail/cat, never re-emitted
# line by line, because several sources end without a newline and must stay
# byte-exact.
#
# Usage: scripts/sync-agents.sh [--check] [--root DIR]
#   --root DIR  directory holding shared/ and the kits (default: repo root)
#
# Exit: 0 ok, 1 drift (sync-agents not yet run), 2 invalid source or usage.

set -uo pipefail

# Glob order, sort order and awk byte handling must not depend on the caller.
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

KIT_HOME=agent/files/home

# Agent frontmatter keys. Widen deliberately: a key that reaches a target
# unreviewed is how a guess becomes a contract.
AGENT_KEYS="name description rules claude.model claude.skills"
AGENT_REQUIRED="name description"

SKILL_KEYS="name description"
SKILL_REQUIRED="name description"

usage() {
	printf 'usage: %s [--check] [--root DIR]\n' "$0" >&2
	exit 2
}

# invalid <shared-relative path> <message>
invalid() {
	printf 'sync-agents: shared/%s: %s\n' "$1" "$2" >&2
}

# marker <source description>
marker() {
	printf '<!-- GENERATED by scripts/sync-agents.sh from shared/%s -- edit that file, not this one -->\n' "$1"
}

# frontmatter_close <file> <mode> [allowed keys] [required keys]
#
# Prints the line number of the closing fence. mode `flat` validates every
# line as `key: value` against the allowlist; mode `opaque` checks only the
# fences and passes the content between them through (a rule's nested
# `paths:` header is Claude path scoping, not ours to interpret).
# On failure prints the reason and returns non-zero.
frontmatter_close() {
	awk -v mode="$2" -v allowed="${3:-}" -v required="${4:-}" '
		function fail(msg) { print "line " NR ": " msg; bad = 1; exit 1 }
		BEGIN {
			n = split(allowed, list, " ")
			for (i = 1; i <= n; i++) ok[list[i]] = 1
		}
		NR == 1 {
			if ($0 != "---") fail("frontmatter must open with --- on line 1")
			next
		}
		/^---+$/ {
			if ($0 != "---") fail("frontmatter must close with exactly ---")
			closed = NR
			exit 0
		}
		mode == "opaque" { next }
		/^[ \t]/ { fail("nested frontmatter is not supported") }
		{
			sep = index($0, ":")
			if (sep < 2) fail("not a flat key: value line")
			key = substr($0, 1, sep - 1)
			value = substr($0, sep + 1)
			if (key !~ /^[a-z][a-z0-9_.-]*$/) fail("not a flat key: value line")
			if (value !~ /^ / && value != "") fail("missing space after " key ":")
			sub(/^ +/, "", value)
			sub(/[ \t]+$/, "", value)
			if (value == "") fail("empty value for " key)
			if (value ~ /^[|>][-+0-9]*$/) fail("block scalar for " key " is not supported")
			if (!(key in ok)) fail("unknown key " key)
			if (key in seen) fail("duplicate key " key)
			seen[key] = 1
		}
		END {
			if (bad) exit 1
			if (!closed) { print "unclosed frontmatter"; exit 1 }
			n = split(required, list, " ")
			for (i = 1; i <= n; i++)
				if (!(list[i] in seen)) { print "missing required key " list[i]; exit 1 }
			print closed
		}
	' "$1"
}

# check_rules_list <shared-relative agent path> <frontmatter key lines file>
#
# `rules: [a, b]` -- bare names, each an existing shared/rules/<name>.md.
check_rules_list() {
	local rel="$1" value name status=0
	value="$(sed -n 's/^rules: *//p' "$2")"
	[[ -z "$value" ]] && return 0
	case "$value" in
	\[*\]) ;;
	*)
		invalid "$rel" "rules must be a [a, b] list"
		return 1
		;;
	esac
	value="${value#[}"
	value="${value%]}"
	# Checked before splitting, so the unquoted expansion below can neither
	# glob nor split on anything but the separators.
	case "$value" in
	*[!a-z0-9,\ -]*)
		invalid "$rel" "rules entries must be bare rule names"
		return 1
		;;
	esac
	for name in $(printf '%s' "$value" | tr ',' ' '); do
		if [[ ! -f "$SHARED/rules/$name.md" ]]; then
			invalid "$rel" "rules entry $name has no shared/rules/$name.md"
			status=1
		fi
	done
	return $status
}

# lint_neutral <shared-relative path>
#
# Neutral sources feed every target, so a Claude path or tool name in them
# leaks into targets where it means nothing.
lint_neutral() {
	local token status=0
	for token in .claude/ subagent_type; do
		if grep -qF -- "$token" "$SHARED/$1"; then
			invalid "$1" "target-specific reference $token in a neutral source"
			status=1
		fi
	done
	return $status
}

# emit_agent <shared-relative path> <output file>
emit_agent() {
	local rel="$1" src="$SHARED/$1" close keys
	if ! close="$(frontmatter_close "$src" flat "$AGENT_KEYS" "$AGENT_REQUIRED")"; then
		invalid "$rel" "$close"
		return 1
	fi
	lint_neutral "$rel" || return 1

	keys="$WORK/keys"
	sed -n "2,$((close - 1))p" "$src" >"$keys"
	check_rules_list "$rel" "$keys" || return 1

	{
		printf -- '---\n'
		# `rules` has no Claude consumer (Claude loads ~/.claude/rules
		# globally); claude.<k> is emitted as <k>.
		awk '{
			key = substr($0, 1, index($0, ":") - 1)
			if (key == "rules") next
			if (key ~ /^claude\./) $0 = substr($0, 8)
			print
		}' "$keys"
		printf -- '---\n'
		marker "$rel"
		tail -n +"$((close + 1))" "$src"
	} >"$2"
}

# emit_rule <shared-relative path> <output file>
#
# The marker goes after a leading frontmatter block (Claude reads it from
# line 1), otherwise on line 1. The block itself is passed through untouched.
emit_rule() {
	local rel="$1" src="$SHARED/$1" close
	if [[ "$(head -n 1 "$src")" != "---" ]]; then
		{
			marker "$rel"
			cat "$src"
		} >"$2"
		return 0
	fi
	if ! close="$(frontmatter_close "$src" opaque)"; then
		invalid "$rel" "$close"
		return 1
	fi
	{
		head -n "$close" "$src"
		marker "$rel"
		tail -n +"$((close + 1))" "$src"
	} >"$2"
}

# emit_skill <shared-relative skill dir> <output dir>
#
# Skills are copied byte for byte with no marker: SKILL.md is a standard
# format both targets read, and only its standard keys are allowed.
emit_skill() {
	local rel="$1" close
	if [[ ! -f "$SHARED/$rel/SKILL.md" ]]; then
		invalid "$rel" "skill directory without SKILL.md"
		return 1
	fi
	if ! close="$(frontmatter_close "$SHARED/$rel/SKILL.md" flat "$SKILL_KEYS" "$SKILL_REQUIRED")"; then
		invalid "$rel/SKILL.md" "$close"
		return 1
	fi
	cp -R "$SHARED/$rel" "$2"
}

# ends_with_newline <shared-relative path> -- concatenated sources must, or
# the next part would be glued onto their last line.
ends_with_newline() {
	if [[ ! -s "$SHARED/$1" ]]; then
		invalid "$1" "missing or empty"
		return 1
	fi
	if [[ -n "$(tail -c 1 "$SHARED/$1")" ]]; then
		invalid "$1" "must end with a newline"
		return 1
	fi
}

# emit_role <output file> -- marker, neutral core, one blank line, the Claude
# delegation-mechanics fragment. Plain concatenation, no templating.
emit_role() {
	local status=0
	ends_with_newline role/ROLE.md || status=1
	ends_with_newline role/delegation.claude.md || status=1
	[[ $status -eq 0 ]] || return 1
	lint_neutral role/ROLE.md || return 1
	{
		marker 'role/ROLE.md + shared/role/delegation.claude.md'
		cat "$SHARED/role/ROLE.md"
		printf '\n'
		cat "$SHARED/role/delegation.claude.md"
	} >"$1"
}

# build <dir> -- generate every owned path under <dir>; non-zero if any source
# is invalid (all diagnostics are printed, not just the first).
build() {
	local out="$1" status=0 src rel
	mkdir -p "$out/.claude/agents" "$out/.claude/rules" "$out/.claude/skills"

	emit_role "$out/ROLE.md" || status=1

	for src in "$SHARED"/agents/*.md; do
		[[ -e "$src" ]] || continue
		rel="agents/${src##*/}"
		emit_agent "$rel" "$out/.claude/agents/${src##*/}" || status=1
	done

	for src in "$SHARED"/rules/*.md; do
		[[ -e "$src" ]] || continue
		rel="rules/${src##*/}"
		emit_rule "$rel" "$out/.claude/rules/${src##*/}" || status=1
	done

	for src in "$SHARED"/skills/*/; do
		[[ -d "$src" ]] || continue
		src="${src%/}"
		rel="skills/${src##*/}"
		emit_skill "$rel" "$out/.claude/skills/${src##*/}" || status=1
	done
	return $status
}

# file_list <base dir> <owned path> -- non-directory entries under it (files
# and symlinks alike, so a stray symlink is drift too), one per line, sorted.
file_list() {
	(cd "$1" && find "$2" ! -type d 2>/dev/null) | sort
}

# report_drift <built home> -- prints `drift: <path>` for every owned file that
# is extra, missing or different in the kit; non-zero if there is any.
report_drift() {
	local built="$1" path f drift=0
	for path in $OWNED; do
		file_list "$built" "$path" >"$WORK/want"
		file_list "$KIT" "$path" >"$WORK/have"
		while IFS= read -r f; do
			printf 'drift: %s/%s (missing)\n' "$KIT_HOME" "$f"
			drift=1
		done < <(comm -23 "$WORK/want" "$WORK/have")
		while IFS= read -r f; do
			printf 'drift: %s/%s (not generated from shared/)\n' "$KIT_HOME" "$f"
			drift=1
		done < <(comm -13 "$WORK/want" "$WORK/have")
		while IFS= read -r f; do
			if ! cmp -s "$built/$f" "$KIT/$f"; then
				printf 'drift: %s/%s (differs)\n' "$KIT_HOME" "$f"
				drift=1
			fi
		done < <(comm -12 "$WORK/want" "$WORK/have")
	done
	return $drift
}

# OWNED: the kit paths this script owns, relative to KIT_HOME.
OWNED="ROLE.md .claude/agents .claude/rules .claude/skills"

check=0
while [[ $# -gt 0 ]]; do
	case "$1" in
	--check) check=1 ;;
	--root)
		[[ $# -ge 2 ]] || usage
		ROOT="$(cd "$2" 2>/dev/null && pwd)" || {
			printf 'sync-agents: --root %s: no such directory\n' "$2" >&2
			exit 2
		}
		shift
		;;
	*) usage ;;
	esac
	shift
done

SHARED="$ROOT/shared"
KIT="$ROOT/$KIT_HOME"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/sync-agents.XXXXXX")" || exit 2
trap 'rm -rf "$WORK"' EXIT
trap 'exit 2' HUP INT TERM

if ! build "$WORK/home"; then
	printf 'sync-agents: invalid source; %s left unchanged\n' "$KIT_HOME" >&2
	exit 2
fi

if [[ $check -eq 1 ]]; then
	if ! report_drift "$WORK/home"; then
		printf 'run: make sync\n'
		exit 1
	fi
	exit 0
fi

for path in $OWNED; do
	mkdir -p "$(dirname "$KIT/$path")"
	rm -rf "${KIT:?}/$path"
	cp -R "$WORK/home/$path" "$KIT/$path"
done
