#!/usr/bin/env bash
#
# Generates the committed kit content from the hand-edited shared/ tree.
#
# shared/ is the single source of truth for the orchestrator role, the
# sub-agents, the rules and the skills. This script is a pure function from
# shared/ to the subtrees it owns in each kit (CLAUDE_OWNED under
# agent/files/home, CODEX_OWNED under agent-codex/files/home); everything else
# in a kit is hand-owned and never read or written.
#
# Sources use a flat YAML frontmatter subset: `key: value` lines only, no
# nesting, no block scalars, keys from an allowlist. Anything else is rejected
# rather than guessed at. Claude bodies are copied with tail/cat, never
# re-emitted line by line, because several sources end without a newline and
# must stay byte-exact.
#
# Codex gets each agent as TOML whose developer_instructions is the body plus
# the rules the agent declares, an AGENTS.md built from the role core, the
# Codex delegation fragment and an index of the rules, and the rules
# themselves (frontmatter stripped) under ~/.jarvis/rules.
#
# Usage: scripts/sync-agents.sh [--check] [--root DIR]
#   --root DIR  directory holding shared/ and the kits (default: repo root)
#
# Exit: 0 ok, 1 drift (sync-agents not yet run), 2 invalid source, usage, or a
# kit path that could not be written.

set -uo pipefail

# Glob order, sort order and awk byte handling must not depend on the caller.
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

CLAUDE_HOME=agent/files/home
CODEX_HOME=agent-codex/files/home

# The kit paths this script owns, relative to each kit home.
CLAUDE_OWNED="ROLE.md .claude/agents .claude/rules .claude/skills"
CODEX_OWNED=".codex/AGENTS.md .codex/agents .agents/skills .jarvis/rules"

# Where the Codex kit's rule files land inside the sandbox; the AGENTS.md
# rules index points here.
CODEX_RULES_DIR=/home/agent/.jarvis/rules

# Codex reads the global and the workspace AGENTS.md together; keep ours small
# enough to leave room for a repo's own.
AGENTS_MD_BUDGET=16384

# Agent frontmatter keys. Widen deliberately: a key that reaches a target
# unreviewed is how a guess becomes a contract. codex.sandbox_mode is left out
# on purpose: Codex does not enforce it per agent under sbx (spike S6).
AGENT_KEYS="name description rules claude.model claude.skills codex.model_reasoning_effort"
AGENT_REQUIRED="name description"

SKILL_KEYS="name description"
SKILL_REQUIRED="name description"

# Control characters TOML strings cannot hold unescaped (tab and LF are fine).
CONTROL_CHARS="$(printf '[\001-\010\013-\037\177]')"

usage() {
	printf 'usage: %s [--check] [--root DIR]\n' "$0" >&2
	exit 2
}

# invalid <shared-relative path> <message>
invalid() {
	printf 'sync-agents: shared/%s: %s\n' "$1" "$2" >&2
}

# marker <source description>
marker() {
	printf '<!-- GENERATED by scripts/sync-agents.sh from shared/%s -- edit that file, not this one -->\n' "$1"
}

# toml_marker <source description>
toml_marker() {
	printf '# GENERATED by scripts/sync-agents.sh from shared/%s -- edit that file, not this one\n' "$1"
}

# frontmatter_close <file> <mode> [allowed keys] [required keys]
#
# Prints the line number of the closing fence. mode `flat` validates every
# line as `key: value` against the allowlist; mode `opaque` checks only the
# fences and passes the content between them through (a rule's nested
# `paths:` header is Claude path scoping, not ours to interpret).
# On failure prints the reason and returns non-zero.
frontmatter_close() {
	awk -v mode="$2" -v allowed="${3:-}" -v required="${4:-}" '
		function fail(msg) { print "line " NR ": " msg; bad = 1; exit 1 }
		BEGIN {
			n = split(allowed, list, " ")
			for (i = 1; i <= n; i++) ok[list[i]] = 1
		}
		NR == 1 {
			if ($0 != "---") fail("frontmatter must open with --- on line 1")
			next
		}
		/^---+$/ {
			if ($0 != "---") fail("frontmatter must close with exactly ---")
			closed = NR
			exit 0
		}
		mode == "opaque" { next }
		/^[ \t]/ { fail("nested frontmatter is not supported") }
		{
			sep = index($0, ":")
			if (sep < 2) fail("not a flat key: value line")
			key = substr($0, 1, sep - 1)
			value = substr($0, sep + 1)
			if (key !~ /^[a-z][a-z0-9_.-]*$/) fail("not a flat key: value line")
			if (value !~ /^ / && value != "") fail("missing space after " key ":")
			sub(/^ +/, "", value)
			sub(/[ \t]+$/, "", value)
			if (value == "") fail("empty value for " key)
			if (value ~ /^[|>][-+0-9]*$/) fail("block scalar for " key " is not supported")
			if (!(key in ok)) fail("unknown key " key)
			if (key in seen) fail("duplicate key " key)
			seen[key] = 1
		}
		END {
			if (bad) exit 1
			if (!closed) { print "unclosed frontmatter"; exit 1 }
			n = split(required, list, " ")
			for (i = 1; i <= n; i++)
				if (!(list[i] in seen)) { print "missing required key " list[i]; exit 1 }
			print closed
		}
	' "$1"
}

# key_value <frontmatter key lines file> <key> -- the trimmed value, or nothing.
key_value() {
	awk -v k="$2" '
		index($0, k ":") == 1 {
			v = substr($0, length(k) + 2)
			sub(/^ +/, "", v)
			sub(/[ \t]+$/, "", v)
			print v
			exit
		}
	' "$1"
}

# rules_of <frontmatter key lines file> -- declared rule names, one per line.
# Only call after check_rules_list accepted the list.
rules_of() {
	key_value "$1" rules | tr -d '[] ' | tr ',' '\n' | sed '/^$/d'
}

# check_rules_list <shared-relative agent path> <frontmatter key lines file>
#
# `rules: [a, b]` -- bare names, each an existing shared/rules/<name>.md.
check_rules_list() {
	local rel="$1" value name status=0
	value="$(sed -n 's/^rules: *//p' "$2")"
	[[ -z "$value" ]] && return 0
	case "$value" in
	\[*\]) ;;
	*)
		invalid "$rel" "rules must be a [a, b] list"
		return 1
		;;
	esac
	value="${value#[}"
	value="${value%]}"
	# Checked before splitting, so the unquoted expansion below can neither
	# glob nor split on anything but the separators.
	case "$value" in
	*[!a-z0-9,\ -]*)
		invalid "$rel" "rules entries must be bare rule names"
		return 1
		;;
	esac
	for name in $(printf '%s' "$value" | tr ',' ' '); do
		if [[ ! -f "$SHARED/rules/$name.md" ]]; then
			invalid "$rel" "rules entry $name has no shared/rules/$name.md"
			status=1
		fi
	done
	return $status
}

# lint_neutral <shared-relative path>
#
# Neutral sources feed every target, so a Claude path or tool name in them
# leaks into targets where it means nothing.
lint_neutral() {
	local token status=0
	for token in .claude/ subagent_type; do
		if grep -qF -- "$token" "$SHARED/$1"; then
			invalid "$1" "target-specific reference $token in a neutral source"
			status=1
		fi
	done
	return $status
}

# no_control_chars <shared-relative path> <file to scan>
no_control_chars() {
	if grep -q "$CONTROL_CHARS" "$2"; then
		invalid "$1" "control character (Codex TOML cannot carry it)"
		return 1
	fi
}

# drop_leading_blank_lines -- stdin to stdout; every line ends in a newline.
drop_leading_blank_lines() {
	awk 'started || NF { started = 1; print }'
}

# toml_string <value> -- the body of a TOML basic string.
toml_string() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# rule_body <shared-relative rule path> -- the rule without any frontmatter.
# Only call after validate_rule accepted the rule.
rule_body() {
	local src="$SHARED/$1" close
	if [[ "$(head -n 1 "$src")" != "---" ]]; then
		cat "$src"
		return 0
	fi
	close="$(frontmatter_close "$src" opaque)"
	tail -n +"$((close + 1))" "$src"
}

# rule_heading <shared-relative rule path> -- text of the first `# ` heading.
rule_heading() {
	rule_body "$1" | awk '/^# / { print substr($0, 3); exit }'
}

# validate_rule <shared-relative rule path>
validate_rule() {
	local rel="$1" src="$SHARED/$1" close
	if [[ "$(head -n 1 "$src")" == "---" ]]; then
		if ! close="$(frontmatter_close "$src" opaque)"; then
			invalid "$rel" "$close"
			return 1
		fi
	fi
	no_control_chars "$rel" "$src" || return 1
	if [[ -z "$(rule_heading "$rel")" ]]; then
		invalid "$rel" "no level-1 (# ) heading to list in the Codex rules index"
		return 1
	fi
}

# emit_agent <shared-relative path> <Claude output file> <Codex agents dir>
emit_agent() {
	local rel="$1" src="$SHARED/$1" close keys name quoted
	if ! close="$(frontmatter_close "$src" flat "$AGENT_KEYS" "$AGENT_REQUIRED")"; then
		invalid "$rel" "$close"
		return 1
	fi
	lint_neutral "$rel" || return 1

	keys="$WORK/keys"
	sed -n "2,$((close - 1))p" "$src" >"$keys"
	check_rules_list "$rel" "$keys" || return 1
	no_control_chars "$rel" "$src" || return 1

	name="$(key_value "$keys" name)"
	case "$name" in
	*[!a-z0-9-]* | -*)
		invalid "$rel" "name $name must be lowercase letters, digits and - (it names the Codex agent file)"
		return 1
		;;
	esac
	# Values reach Codex as TOML strings verbatim, so a YAML-quoted value
	# would keep its quotes there.
	quoted="$(awk '/^(name|description|codex\.[a-z_]+): *["\047]/ { print substr($0, 1, index($0, ":") - 1); exit }' "$keys")"
	if [[ -n "$quoted" ]]; then
		invalid "$rel" "quoted value for $quoted is not supported (it would reach Codex with its quotes)"
		return 1
	fi
	if [[ -e "$3/$name.toml" ]]; then
		invalid "$rel" "another agent is already named $name"
		return 1
	fi

	{
		printf -- '---\n'
		# `rules` has no Claude consumer (Claude loads ~/.claude/rules
		# globally); claude.<k> is emitted as <k>; codex.<k> is not Claude's.
		awk '{
			key = substr($0, 1, index($0, ":") - 1)
			if (key == "rules" || key ~ /^codex\./) next
			if (key ~ /^claude\./) $0 = substr($0, 8)
			print
		}' "$keys"
		printf -- '---\n'
		marker "$rel"
		tail -n +"$((close + 1))" "$src"
	} >"$2"

	emit_codex_agent "$rel" "$close" "$keys" "$3/$name.toml"
}

# emit_codex_agent <shared-relative path> <closing fence line> <key lines file> <output file>
#
# developer_instructions = body, then each declared rule in declared order,
# one blank line between parts. Written as a multi-line basic string with `\`
# and `"""` escaped; control characters were rejected before we got here.
emit_codex_agent() {
	local rel="$1" src="$SHARED/$1" instr="$WORK/instructions" rule
	tail -n +"$(($2 + 1))" "$src" | drop_leading_blank_lines >"$instr"
	for rule in $(rules_of "$3"); do
		[[ -s "$instr" ]] && printf '\n' >>"$instr"
		rule_body "rules/$rule.md" | drop_leading_blank_lines >>"$instr"
	done

	{
		toml_marker "$rel"
		printf 'name = "%s"\n' "$(toml_string "$(key_value "$3" name)")"
		printf 'description = "%s"\n' "$(toml_string "$(key_value "$3" description)")"
		awk '/^codex\./ {
			sep = index($0, ":")
			v = substr($0, sep + 1)
			sub(/^ +/, "", v)
			sub(/[ \t]+$/, "", v)
			print substr($0, 7, sep - 7) "\t" v
		}' "$3" | while IFS="$(printf '\t')" read -r key value; do
			printf '%s = "%s"\n' "$key" "$(toml_string "$value")"
		done
		printf 'developer_instructions = """\n'
		sed -e 's/\\/\\\\/g' -e 's/"""/""\\"/g' "$instr"
		printf '"""\n'
	} >"$4"
}

# emit_rule <shared-relative path> <Claude output file> <Codex output file>
#
# Claude: the marker goes after a leading frontmatter block (Claude reads it
# from line 1), otherwise on line 1; the block itself is passed through
# untouched. Codex: the block is Claude path scoping and noise in a prompt, so
# it is dropped and the marker goes on line 1.
emit_rule() {
	local rel="$1" src="$SHARED/$1" close
	validate_rule "$rel" || return 1
	{
		marker "$rel"
		rule_body "$rel"
	} >"$3"
	if [[ "$(head -n 1 "$src")" != "---" ]]; then
		{
			marker "$rel"
			cat "$src"
		} >"$2"
		return 0
	fi
	close="$(frontmatter_close "$src" opaque)"
	{
		head -n "$close" "$src"
		marker "$rel"
		tail -n +"$((close + 1))" "$src"
	} >"$2"
}

# emit_skill <shared-relative skill dir> <Claude output dir> <Codex output dir>
#
# Skills are copied byte for byte with no marker: SKILL.md is a standard
# format both targets read, and only its standard keys are allowed.
emit_skill() {
	local rel="$1" close
	if [[ ! -f "$SHARED/$rel/SKILL.md" ]]; then
		invalid "$rel" "skill directory without SKILL.md"
		return 1
	fi
	if ! close="$(frontmatter_close "$SHARED/$rel/SKILL.md" flat "$SKILL_KEYS" "$SKILL_REQUIRED")"; then
		invalid "$rel/SKILL.md" "$close"
		return 1
	fi
	cp -R "$SHARED/$rel" "$2"
	cp -R "$SHARED/$rel" "$3"
}

# ends_with_newline <shared-relative path> -- concatenated sources must, or
# the next part would be glued onto their last line.
ends_with_newline() {
	if [[ ! -s "$SHARED/$1" ]]; then
		invalid "$1" "missing or empty"
		return 1
	fi
	if [[ -n "$(tail -c 1 "$SHARED/$1")" ]]; then
		invalid "$1" "must end with a newline"
		return 1
	fi
}

# emit_role <output file> -- marker, neutral core, one blank line, the Claude
# delegation-mechanics fragment. Plain concatenation, no templating.
emit_role() {
	local status=0
	ends_with_newline role/ROLE.md || status=1
	ends_with_newline role/delegation.claude.md || status=1
	[[ $status -eq 0 ]] || return 1
	lint_neutral role/ROLE.md || return 1
	{
		marker 'role/ROLE.md + shared/role/delegation.claude.md'
		cat "$SHARED/role/ROLE.md"
		printf '\n'
		cat "$SHARED/role/delegation.claude.md"
	} >"$1"
}

# emit_agents_md <output file> -- marker, neutral core, one blank line, the
# Codex delegation fragment, one blank line, the rules index. Fails above
# AGENTS_MD_BUDGET bytes rather than let Codex truncate it.
emit_agents_md() {
	local status=0 src name size
	ends_with_newline role/ROLE.md || status=1
	ends_with_newline role/delegation.codex.md || status=1
	[[ $status -eq 0 ]] || return 1
	{
		marker 'role/ROLE.md + shared/role/delegation.codex.md + rules index'
		cat "$SHARED/role/ROLE.md"
		printf '\n'
		cat "$SHARED/role/delegation.codex.md"
		printf '\n## Rules index\n\n'
		for src in "$SHARED"/rules/*.md; do
			[[ -e "$src" ]] || continue
			name="${src##*/}"
			name="${name%.md}"
			printf -- '- `%s`: %s (`%s/%s.md`)\n' "$name" "$(rule_heading "rules/$name.md")" "$CODEX_RULES_DIR" "$name"
		done
	} >"$1"
	size="$(wc -c <"$1" | tr -d ' ')"
	if [[ "$size" -gt "$AGENTS_MD_BUDGET" ]]; then
		invalid role/ROLE.md "Codex AGENTS.md would be $size bytes, over the $AGENTS_MD_BUDGET-byte budget"
		return 1
	fi
}

# build <dir> -- generate every owned path under <dir>/claude and <dir>/codex;
# non-zero if any source is invalid. All diagnostics of a stage are printed,
# not just the first; an invalid rule stops before the agents that inline it.
build() {
	local claude="$1/claude" codex="$1/codex" status=0 src rel rules_ok=1
	mkdir -p "$claude/.claude/agents" "$claude/.claude/rules" "$claude/.claude/skills" \
		"$codex/.codex/agents" "$codex/.agents/skills" "$codex/.jarvis/rules"

	emit_role "$claude/ROLE.md" || status=1

	# Rules first: agents inline them, and the index lists them.
	for src in "$SHARED"/rules/*.md; do
		[[ -e "$src" ]] || continue
		rel="rules/${src##*/}"
		emit_rule "$rel" "$claude/.claude/rules/${src##*/}" "$codex/.jarvis/rules/${src##*/}" || rules_ok=0
	done
	[[ $rules_ok -eq 1 ]] || return 1

	for src in "$SHARED"/agents/*.md; do
		[[ -e "$src" ]] || continue
		rel="agents/${src##*/}"
		emit_agent "$rel" "$claude/.claude/agents/${src##*/}" "$codex/.codex/agents" || status=1
	done

	for src in "$SHARED"/skills/*/; do
		[[ -d "$src" ]] || continue
		src="${src%/}"
		rel="skills/${src##*/}"
		emit_skill "$rel" "$claude/.claude/skills/${src##*/}" "$codex/.agents/skills/${src##*/}" || status=1
	done

	emit_agents_md "$codex/.codex/AGENTS.md" || status=1
	return $status
}

# file_list <base dir> <owned path> -- non-directory entries under it (files
# and symlinks alike, so a stray symlink is drift too), one per line, sorted.
file_list() {
	(cd "$1" && find "$2" ! -type d 2>/dev/null) | sort
}

# report_drift <built home> <kit home, root-relative> <owned paths> -- prints
# `drift: <path>` for every owned file that is extra, missing or different in
# the kit; non-zero if there is any.
report_drift() {
	local built="$1" home="$2" kit="$ROOT/$2" path f drift=0
	for path in $3; do
		file_list "$built" "$path" >"$WORK/want"
		file_list "$kit" "$path" >"$WORK/have"
		while IFS= read -r f; do
			printf 'drift: %s/%s (missing)\n' "$home" "$f"
			drift=1
		done < <(comm -23 "$WORK/want" "$WORK/have")
		while IFS= read -r f; do
			printf 'drift: %s/%s (not generated from shared/)\n' "$home" "$f"
			drift=1
		done < <(comm -13 "$WORK/want" "$WORK/have")
		while IFS= read -r f; do
			if ! cmp -s "$built/$f" "$kit/$f"; then
				printf 'drift: %s/%s (differs)\n' "$home" "$f"
				drift=1
			fi
		done < <(comm -12 "$WORK/want" "$WORK/have")
	done
	return $drift
}

# install_owned <built home> <kit home, root-relative> <owned paths> -- non-zero
# on the first path it cannot replace.
install_owned() {
	local built="$1" kit="$ROOT/$2" path
	for path in $3; do
		mkdir -p "$(dirname "$kit/$path")" &&
			rm -rf "${kit:?}/$path" &&
			cp -R "$built/$path" "$kit/$path" || {
			printf 'sync-agents: could not write %s/%s\n' "$2" "$path" >&2
			return 1
		}
	done
}

check=0
while [[ $# -gt 0 ]]; do
	case "$1" in
	--check) check=1 ;;
	--root)
		[[ $# -ge 2 ]] || usage
		ROOT="$(cd "$2" 2>/dev/null && pwd)" || {
			printf 'sync-agents: --root %s: no such directory\n' "$2" >&2
			exit 2
		}
		shift
		;;
	*) usage ;;
	esac
	shift
done

SHARED="$ROOT/shared"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/sync-agents.XXXXXX")" || exit 2
trap 'rm -rf "$WORK"' EXIT
trap 'exit 2' HUP INT TERM

if ! build "$WORK/out"; then
	printf 'sync-agents: invalid source; %s and %s left unchanged\n' "$CLAUDE_HOME" "$CODEX_HOME" >&2
	exit 2
fi

if [[ $check -eq 1 ]]; then
	drift=0
	report_drift "$WORK/out/claude" "$CLAUDE_HOME" "$CLAUDE_OWNED" || drift=1
	report_drift "$WORK/out/codex" "$CODEX_HOME" "$CODEX_OWNED" || drift=1
	if [[ $drift -ne 0 ]]; then
		printf 'run: make sync\n'
		exit 1
	fi
	exit 0
fi

install_owned "$WORK/out/claude" "$CLAUDE_HOME" "$CLAUDE_OWNED" &&
	install_owned "$WORK/out/codex" "$CODEX_HOME" "$CODEX_OWNED" || exit 2
