#!/usr/bin/env bash
#
# Acceptance tests for scripts/sync-agents.sh, the generator that turns the
# hand-edited shared/ tree into the committed kit content under
# agent/files/home (Claude) and agent-codex/files/home (Codex).
#
# Every case builds its own fixture (a shared/ tree plus a kit with hand-owned
# files) in a fresh temp directory, runs the generator against it with --root,
# and asserts the exit class and the observable output: generated bytes, the
# file named in a diagnostic, or the kit left untouched. Full message text is
# not asserted.
#
# The generator runs under "$BASH", the interpreter running this suite, so
# `/bin/bash scripts/test-sync-agents.sh` exercises bash 3.2 on macOS.
#
# Usage: scripts/test-sync-agents.sh [filter]
#   filter: run only the cases whose name contains this substring
#           (group names: emit, codex, reject, sync, check, determinism)

set -uo pipefail

cd "$(dirname "$0")/.."

GEN="$PWD/scripts/sync-agents.sh"
FILTER="${1:-}"

TEST_TMP="$(mktemp -d "${TMPDIR:-/tmp}/test-sync-agents.XXXXXX")"
trap 'rm -rf "$TEST_TMP"' EXIT

pass=0
fail=0
case_seq=0

KIT_HOME=agent/files/home
CODEX_HOME=agent-codex/files/home

# Fixture sources, as printf %b strings. Two of them deliberately end without
# a newline: real sources do (ROLE.md, planner.md, two rules, two skills), and
# the generator must not add one.
SRC_ROLE='# Role\n\nCore text.\n'
SRC_DELEGATION='## Delegation mechanics (Claude Code)\n\nThe sub-agents are defined in `.claude/agents`.\n'
SRC_DELEGATION_CODEX='## Delegation mechanics (Codex)\n\nThe sub-agents are in `~/.codex/agents`.\n'
SRC_ALPHA='---\nname: jarvis-alpha\ndescription: Alpha agent \xe2\x80\x94 does a, b: c.\nclaude.model: sonnet\ncodex.model_reasoning_effort: high\n---\n\n# Alpha\n\nBody.\n'
SRC_BETA='---\nname: jarvis-beta\ndescription: Beta agent.\nrules: [plain]\nclaude.skills: ["a:b"]\n---\n\n# Beta\n\nBody without a trailing newline.'
SRC_RULE_PLAIN='# Plain\n\nRule text.\n'
SRC_RULE_SCOPED='---\npaths:\n  - "**/*.go"\n---\n\n# Scoped\n\nGo rule.'
SRC_SKILL="---\nname: demo\ndescription: 'Demo skill.'\n---\n\nSkill body."
SRC_SKILL_REF='reference notes\n'

# Hand-owned kit files: never read or written by the generator.
HAND_SPEC='name: fixture\n'
HAND_ROLE_LABEL='ENGINEER\n'
HAND_SETTINGS='{"model": "opus"}\n'
HAND_WORKFLOW='export default {};\n'
HAND_CODEX_SPEC='name: fixture-codex\n'

# marker_text <source description> -- the generated-file marker, no newline.
marker_text() {
	printf '<!-- GENERATED by scripts/sync-agents.sh from shared/%s -- edit that file, not this one -->' "$1"
}

# toml_marker_text <source description> -- the marker as a TOML comment, no newline.
toml_marker_text() {
	printf '# GENERATED by scripts/sync-agents.sh from shared/%s -- edit that file, not this one' "$1"
}

# Expected TOML pieces, as printf %b strings: Q3 is the """ delimiter.
Q3='\x22\x22\x22'

# put <file> <printf-%b content> -- write a file, creating its directory.
put() {
	mkdir -p "$(dirname "$1")"
	printf '%b' "$2" >"$1"
}

# make_fixture <dir>
make_fixture() {
	local fx="$1"
	put "$fx/shared/role/ROLE.md" "$SRC_ROLE"
	put "$fx/shared/role/delegation.claude.md" "$SRC_DELEGATION"
	put "$fx/shared/role/delegation.codex.md" "$SRC_DELEGATION_CODEX"
	put "$fx/shared/agents/alpha.md" "$SRC_ALPHA"
	put "$fx/shared/agents/beta.md" "$SRC_BETA"
	put "$fx/shared/rules/plain.md" "$SRC_RULE_PLAIN"
	put "$fx/shared/rules/scoped.md" "$SRC_RULE_SCOPED"
	put "$fx/shared/skills/demo/SKILL.md" "$SRC_SKILL"
	put "$fx/shared/skills/demo/ref/notes.txt" "$SRC_SKILL_REF"
	put "$fx/agent/spec.yaml" "$HAND_SPEC"
	put "$fx/$KIT_HOME/.jarvis-role" "$HAND_ROLE_LABEL"
	put "$fx/$KIT_HOME/.claude/settings.json" "$HAND_SETTINGS"
	put "$fx/$KIT_HOME/.claude/workflows/x.js" "$HAND_WORKFLOW"
	put "$fx/agent-codex/spec.yaml" "$HAND_CODEX_SPEC"
	put "$fx/$CODEX_HOME/.jarvis-role" "$HAND_ROLE_LABEL"
}

# gen <fixture> [args...] -- run the generator; sets $out (stdout+stderr), $rc.
gen() {
	local fx="$1"
	shift
	out="$("$BASH" "$GEN" --root "$fx" "$@" 2>&1)"
	rc=$?
}

# tree_sum <dir> -- one checksum line per file, path-sorted; content only.
tree_sum() {
	(cd "$1" && find . -type f | LC_ALL=C sort | while IFS= read -r f; do
		printf '%s %s\n' "$(cksum <"$f")" "$f"
	done)
}

# kits_sum <fixture> -- tree_sum of both kits.
kits_sum() {
	tree_sum "$1/agent"
	tree_sum "$1/agent-codex"
}

# ---- assertion helpers: return 0 on success, print the reason otherwise ----

expect_rc() {
	if [[ "$rc" -ne "$1" ]]; then
		printf 'exit %s, want %s; output: %s' "$rc" "$1" "${out:-<empty>}"
		return 1
	fi
}

expect_output_names() {
	if [[ "$out" != *"$1"* ]]; then
		printf 'output does not name %s; output: %s' "$1" "${out:-<empty>}"
		return 1
	fi
}

# expect_bytes <actual file> <printf-%b expected content>
expect_bytes() {
	local want="$TEST_TMP/want.$$"
	printf '%b' "$2" >"$want"
	if [[ ! -f "$1" ]]; then
		printf 'missing file %s' "$1"
		return 1
	fi
	if ! cmp -s "$want" "$1"; then
		printf 'bytes differ for %s:\n%s' "$1" "$(diff "$want" "$1")"
		return 1
	fi
}

# run_case <name> <function> [args...]
#
# Builds a fresh fixture and calls <function> <fixture> [args...]. The function
# prints a reason and returns non-zero on failure.
run_case() {
	local name="$1" fn="$2" fx reason
	shift 2
	[[ -n "$FILTER" && "$name" != *"$FILTER"* ]] && return 0

	case_seq=$((case_seq + 1))
	fx="$TEST_TMP/case-$case_seq"
	make_fixture "$fx"

	if reason="$("$fn" "$fx" "$@")"; then
		printf 'ok   %s\n' "$name"
		pass=$((pass + 1))
	else
		printf 'FAIL %s\n     %s\n' "$name" "$reason"
		fail=$((fail + 1))
	fi
}

# ---- case bodies ----

# generates <fixture> <kit-home-relative path> <printf-%b expected content>
generates() {
	gen "$1"
	expect_rc 0 || return 1
	expect_bytes "$1/$KIT_HOME/$2" "$3"
}

# generated_line <fixture> <kit-home-relative path> <line number> <expected line>
generated_line() {
	local got
	gen "$1"
	expect_rc 0 || return 1
	if [[ ! -f "$1/$KIT_HOME/$2" ]]; then
		printf 'missing file %s' "$2"
		return 1
	fi
	got="$(sed -n "$3p" "$1/$KIT_HOME/$2")"
	if [[ "$got" != "$4" ]]; then
		printf 'line %s of %s is %s, want %s' "$3" "$2" "${got:-<empty>}" "$4"
		return 1
	fi
}

# generates_codex <fixture> <codex-kit-home-relative path> <printf-%b expected content>
generates_codex() {
	gen "$1"
	expect_rc 0 || return 1
	expect_bytes "$1/$CODEX_HOME/$2" "$3"
}

# emits_codex_agent <fixture> <shared-relative agent> <printf-%b source> <toml file> <printf-%b expected>
emits_codex_agent() {
	put "$1/shared/$2" "$3"
	generates_codex "$1" ".codex/agents/$4" "$5"
}

copies_skill_tree_to_codex() {
	gen "$1"
	expect_rc 0 || return 1
	if ! diff -r "$1/shared/skills/demo" "$1/$CODEX_HOME/.agents/skills/demo" >/dev/null 2>&1; then
		printf 'skill tree differs: %s' "$(diff -r "$1/shared/skills/demo" "$1/$CODEX_HOME/.agents/skills/demo" 2>&1)"
		return 1
	fi
}

no_rules_key_in_agents() {
	gen "$1"
	expect_rc 0 || return 1
	if grep -l '^rules:' "$1/$KIT_HOME/.claude/agents/"*.md; then
		printf 'a generated agent carries a rules: line'
		return 1
	fi
}

copies_skill_tree() {
	gen "$1"
	expect_rc 0 || return 1
	if ! diff -r "$1/shared/skills/demo" "$1/$KIT_HOME/.claude/skills/demo" >/dev/null 2>&1; then
		printf 'skill tree differs: %s' "$(diff -r "$1/shared/skills/demo" "$1/$KIT_HOME/.claude/skills/demo" 2>&1)"
		return 1
	fi
}

# rejects <fixture> <shared-relative source> <printf-%b content>
#
# Replaces one source file with invalid content; the generator must exit 2 and
# name that source in its diagnostic.
rejects() {
	put "$1/shared/$2" "$3"
	gen "$1"
	expect_rc 2 || return 1
	expect_output_names "shared/$2"
}

rejects_usage() {
	gen "$1" --no-such-option
	expect_rc 2
}

invalid_source_leaves_kit_unchanged() {
	local before after
	gen "$1"
	expect_rc 0 || return 1
	before="$(kits_sum "$1")"
	put "$1/shared/agents/alpha.md" '---\nname: jarvis-alpha\ndescription: d\ncolor: red\n---\n'
	put "$1/shared/rules/plain.md" '# Plain, edited\n'
	gen "$1"
	expect_rc 2 || return 1
	after="$(kits_sum "$1")"
	if [[ "$before" != "$after" ]]; then
		printf 'kit changed after a rejected run'
		return 1
	fi
}

second_run_is_a_no_op() {
	local first second
	gen "$1"
	expect_rc 0 || return 1
	first="$(kits_sum "$1")"
	gen "$1"
	expect_rc 0 || return 1
	second="$(kits_sum "$1")"
	if [[ "$first" != "$second" ]]; then
		printf 'second run changed the kit'
		return 1
	fi
}

removed_source_removes_output() {
	gen "$1"
	expect_rc 0 || return 1
	rm "$1/shared/agents/beta.md" "$1/shared/rules/scoped.md"
	gen "$1"
	expect_rc 0 || return 1
	local f
	for f in $KIT_HOME/.claude/agents/beta.md $KIT_HOME/.claude/rules/scoped.md \
		$CODEX_HOME/.codex/agents/jarvis-beta.toml $CODEX_HOME/.jarvis/rules/scoped.md; do
		if [[ -e "$1/$f" ]]; then
			printf '%s survived the removal of its source' "$f"
			return 1
		fi
	done
}

failed_write_is_an_error() {
	gen "$1"
	expect_rc 0 || return 1
	printf '\nedited\n' >>"$1/shared/rules/plain.md"
	chmod a-w "$1/$KIT_HOME/.claude/rules"
	gen "$1"
	chmod u+w "$1/$KIT_HOME/.claude/rules"
	if [[ "$rc" -eq 0 ]]; then
		printf 'exit 0 although the kit could not be written; output: %s' "${out:-<empty>}"
		return 1
	fi
}

hand_owned_untouched() {
	gen "$1"
	expect_rc 0 || return 1
	expect_bytes "$1/agent/spec.yaml" "$HAND_SPEC" &&
		expect_bytes "$1/$KIT_HOME/.jarvis-role" "$HAND_ROLE_LABEL" &&
		expect_bytes "$1/$KIT_HOME/.claude/settings.json" "$HAND_SETTINGS" &&
		expect_bytes "$1/$KIT_HOME/.claude/workflows/x.js" "$HAND_WORKFLOW" &&
		expect_bytes "$1/agent-codex/spec.yaml" "$HAND_CODEX_SPEC" &&
		expect_bytes "$1/$CODEX_HOME/.jarvis-role" "$HAND_ROLE_LABEL"
}

check_passes_when_fresh() {
	gen "$1"
	expect_rc 0 || return 1
	gen "$1" --check
	expect_rc 0
}

# check_detects <fixture> <edit: append|extra|symlink|remove> <kit-home-relative path>
check_detects() {
	check_detects_in "$1" "$KIT_HOME" "$2" "$3"
}

# check_detects_codex <fixture> <edit> <codex-kit-home-relative path>
check_detects_codex() {
	check_detects_in "$1" "$CODEX_HOME" "$2" "$3"
}

# check_detects_in <fixture> <kit home> <edit: append|extra|symlink|remove> <path under it>
check_detects_in() {
	gen "$1"
	expect_rc 0 || return 1
	case "$3" in
	append) printf 'hand edit\n' >>"$1/$2/$4" ;;
	extra) put "$1/$2/$4" 'stray\n' ;;
	symlink) ln -s ../rules/plain.md "$1/$2/$4" ;;
	remove) rm -r "$1/$2/$4" ;;
	esac
	gen "$1" --check
	expect_rc 1 || return 1
	expect_output_names "$2/$4"
}

check_ignores_hand_owned() {
	gen "$1"
	expect_rc 0 || return 1
	printf 'edited\n' >>"$1/agent/spec.yaml"
	printf 'edited\n' >>"$1/$KIT_HOME/.jarvis-role"
	printf 'edited\n' >>"$1/$KIT_HOME/.claude/settings.json"
	printf 'edited\n' >>"$1/$KIT_HOME/.claude/workflows/x.js"
	put "$1/$KIT_HOME/.claude/workflows/new.js" 'new\n'
	printf 'edited\n' >>"$1/agent-codex/spec.yaml"
	printf 'edited\n' >>"$1/$CODEX_HOME/.jarvis-role"
	gen "$1" --check
	expect_rc 0
}

check_is_read_only() {
	local scratch="$1/scratch-tmp" before after leftover
	mkdir -p "$scratch"
	gen "$1"
	expect_rc 0 || return 1
	printf 'hand edit\n' >>"$1/$KIT_HOME/.claude/rules/plain.md"
	before="$(kits_sum "$1")"
	out="$(TMPDIR="$scratch" "$BASH" "$GEN" --root "$1" --check 2>&1)"
	rc=$?
	expect_rc 1 || return 1
	after="$(kits_sum "$1")"
	if [[ "$before" != "$after" ]]; then
		printf -- '--check modified the kit'
		return 1
	fi
	leftover="$(ls -A "$scratch")"
	if [[ -n "$leftover" ]]; then
		printf -- '--check left temp entries behind: %s' "$leftover"
		return 1
	fi
}

same_output_across_locales() {
	local other="$1-other" a b
	make_fixture "$other"
	out="$(LC_ALL=C "$BASH" "$GEN" --root "$1" 2>&1)"
	rc=$?
	expect_rc 0 || return 1
	out="$(LC_ALL=en_US.UTF-8 "$BASH" "$GEN" --root "$other" 2>&1)"
	rc=$?
	expect_rc 0 || return 1
	a="$(kits_sum "$1")"
	b="$(kits_sum "$other")"
	if [[ "$a" != "$b" ]]; then
		printf 'output differs between LC_ALL=C and LC_ALL=en_US.UTF-8'
		return 1
	fi
}

# ---- the table ----

printf '== sync-agents acceptance ==\n'

run_case "emit: writes name/description unchanged and maps claude.model to model:" \
	generates .claude/agents/alpha.md \
	"---\nname: jarvis-alpha\ndescription: Alpha agent \xe2\x80\x94 does a, b: c.\nmodel: sonnet\n---\n$(marker_text agents/alpha.md)\n\n# Alpha\n\nBody.\n"
run_case "emit: passes list values through byte for byte" \
	generated_line .claude/agents/beta.md 4 'skills: ["a:b"]'
run_case "emit: drops the rules: key from Claude agent files" \
	no_rules_key_in_agents
run_case "emit: places the marker right after the closing fence" \
	generated_line .claude/agents/alpha.md 6 "$(marker_text agents/alpha.md)"
run_case "emit: places the marker on line 1 of a file with no frontmatter" \
	generated_line .claude/rules/plain.md 1 "$(marker_text rules/plain.md)"
run_case "emit: keeps a body without a trailing newline without one" \
	generates .claude/agents/beta.md \
	"---\nname: jarvis-beta\ndescription: Beta agent.\nskills: [\"a:b\"]\n---\n$(marker_text agents/beta.md)\n\n# Beta\n\nBody without a trailing newline."
run_case "emit: keeps a rule's nested frontmatter first and puts the marker after it" \
	generates .claude/rules/scoped.md \
	"---\npaths:\n  - \"**/*.go\"\n---\n$(marker_text rules/scoped.md)\n\n# Scoped\n\nGo rule."
run_case "emit: copies skill directories byte for byte, with no marker" \
	copies_skill_tree
run_case "emit: concatenates role core, one blank line, delegation.claude.md into ROLE.md" \
	generates ROLE.md \
	"$(marker_text 'role/ROLE.md + shared/role/delegation.claude.md')\n${SRC_ROLE}\n${SRC_DELEGATION}"

run_case "codex: writes an agent TOML with marker, strings, codex keys and the body" \
	generates_codex .codex/agents/jarvis-alpha.toml \
	"$(toml_marker_text agents/alpha.md)"'\nname = "jarvis-alpha"\ndescription = "Alpha agent \xe2\x80\x94 does a, b: c."\nmodel_reasoning_effort = "high"\ndeveloper_instructions = '"$Q3"'\n# Alpha\n\nBody.\n'"$Q3"'\n'
run_case "codex: inlines declared rules after the body and drops claude.* keys" \
	generates_codex .codex/agents/jarvis-beta.toml \
	"$(toml_marker_text agents/beta.md)"'\nname = "jarvis-beta"\ndescription = "Beta agent."\ndeveloper_instructions = '"$Q3"'\n# Beta\n\nBody without a trailing newline.\n\n# Plain\n\nRule text.\n'"$Q3"'\n'
run_case "codex: inlines rules in declared order, without their frontmatter" \
	emits_codex_agent agents/beta.md '---\nname: jarvis-beta\ndescription: Beta agent.\nrules: [scoped, plain]\n---\n\nBody.\n' jarvis-beta.toml \
	"$(toml_marker_text agents/beta.md)"'\nname = "jarvis-beta"\ndescription = "Beta agent."\ndeveloper_instructions = '"$Q3"'\nBody.\n\n# Scoped\n\nGo rule.\n\n# Plain\n\nRule text.\n'"$Q3"'\n'
run_case "codex: escapes backslashes and triple quotes in instructions, quotes in strings" \
	emits_codex_agent agents/alpha.md '---\nname: jarvis-alpha\ndescription: Say "hi" to C:\\dir.\n---\n\nPath C:\\dir and """q"""\n' jarvis-alpha.toml \
	"$(toml_marker_text agents/alpha.md)"'\nname = "jarvis-alpha"\ndescription = "Say \\"hi\\" to C:\\\\dir."\ndeveloper_instructions = '"$Q3"'\nPath C:\\\\dir and ""\\"q""\\"\n'"$Q3"'\n'
run_case "codex: writes a rule with frontmatter as marker plus the body, no frontmatter" \
	generates_codex .jarvis/rules/scoped.md \
	"$(marker_text rules/scoped.md)"'\n\n# Scoped\n\nGo rule.'
run_case "codex: writes a rule without frontmatter with the marker on line 1" \
	generates_codex .jarvis/rules/plain.md \
	"$(marker_text rules/plain.md)\n${SRC_RULE_PLAIN}"
run_case "codex: builds AGENTS.md from role core, delegation.codex.md and a rules index" \
	generates_codex .codex/AGENTS.md \
	"$(marker_text 'role/ROLE.md + shared/role/delegation.codex.md + rules index')\n${SRC_ROLE}\n${SRC_DELEGATION_CODEX}\n"'## Rules index\n\n- `plain`: Plain (`/home/agent/.jarvis/rules/plain.md`)\n- `scoped`: Scoped (`/home/agent/.jarvis/rules/scoped.md`)\n'
run_case "codex: copies skill directories to .agents/skills byte for byte" \
	copies_skill_tree_to_codex

run_case "reject: unknown frontmatter key" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\ncolor: red\n---\n\nBody.\n'
run_case "reject: indented (nested) frontmatter line in an agent" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n  claude.model: sonnet\n---\n\nBody.\n'
run_case "reject: block scalar | in an agent" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: |\n  multi\n---\n\nBody.\n'
run_case "reject: block scalar > in an agent" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: >\n  folded\n---\n\nBody.\n'
run_case "reject: agent frontmatter closed by a dash run" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n----------\n\nBody.\n'
run_case "reject: rule frontmatter closed by a dash run" \
	rejects rules/scoped.md '---\npaths:\n  - "**/*.go"\n-----\n\nGo rule.\n'
run_case "reject: unclosed agent frontmatter" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n\nBody.\n'
run_case "reject: agent without frontmatter" \
	rejects agents/alpha.md '# Alpha\n\nBody.\n'
run_case "reject: missing name" \
	rejects agents/alpha.md '---\ndescription: d\n---\n\nBody.\n'
run_case "reject: missing description" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\n---\n\nBody.\n'
run_case "reject: duplicate key" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\nname: jarvis-again\ndescription: d\n---\n\nBody.\n'
run_case "reject: empty value" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\nclaude.model:\n---\n\nBody.\n'
run_case "reject: rules: entry with no shared/rules/<name>.md" \
	rejects agents/beta.md '---\nname: jarvis-beta\ndescription: d\nrules: [plain, nope]\n---\n\nBody.\n'
run_case "reject: rules: entry that is not a bare name" \
	rejects agents/beta.md '---\nname: jarvis-beta\ndescription: d\nrules: ["plain"]\n---\n\nBody.\n'
run_case "reject: .claude/ in a neutral agent body" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n---\n\nSee .claude/agents.\n'
run_case "reject: subagent_type in a neutral agent body" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n---\n\nPass subagent_type here.\n'
run_case "reject: .claude/ in the neutral role core" \
	rejects role/ROLE.md '# Role\n\nAgents live in .claude/agents.\n'
run_case "reject: role core without a trailing newline" \
	rejects role/ROLE.md '# Role\n\nCore text.'
run_case "reject: delegation fragment without a trailing newline" \
	rejects role/delegation.claude.md '## Delegation\n\nText.'
run_case "reject: skill with a key outside name, description" \
	rejects skills/demo/SKILL.md "---\nname: demo\ndescription: 'Demo.'\nmodel: sonnet\n---\n\nSkill body.\n"
run_case "reject: codex.sandbox_mode (Codex does not enforce it per agent)" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\ncodex.sandbox_mode: read-only\n---\n\nBody.\n'
run_case "reject: agent name that is not a safe file name" \
	rejects agents/alpha.md '---\nname: Jarvis/Alpha\ndescription: d\n---\n\nBody.\n'
run_case "reject: quoted agent description (Codex would keep the quotes)" \
	rejects agents/alpha.md "---\nname: jarvis-alpha\ndescription: 'Quoted.'\n---\n\nBody.\n"
run_case "reject: two agents with the same name" \
	rejects agents/beta.md '---\nname: jarvis-alpha\ndescription: d\n---\n\nBody.\n'
run_case "reject: control character in an agent body" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d\n---\n\nBell \001 here.\n'
run_case "reject: control character in an agent description" \
	rejects agents/alpha.md '---\nname: jarvis-alpha\ndescription: d \033 e\n---\n\nBody.\n'
run_case "reject: control character in a rule" \
	rejects rules/plain.md '# Plain\n\nBell \001 here.\n'
run_case "reject: rule without a level-1 heading" \
	rejects rules/plain.md 'Rule text only.\n'
run_case "reject: codex delegation fragment without a trailing newline" \
	rejects role/delegation.codex.md '## Delegation\n\nText.'
run_case "reject: Codex AGENTS.md over the byte budget" \
	rejects role/ROLE.md "# Role\n\n$(head -c 17000 /dev/zero | tr '\0' x)\n"
run_case "reject: unknown option is a usage error" \
	rejects_usage
run_case "reject: invalid source leaves the kit directory unchanged" \
	invalid_source_leaves_kit_unchanged

run_case "sync: a second run changes nothing" \
	second_run_is_a_no_op
run_case "sync: a removed source removes its generated file" \
	removed_source_removes_output
run_case "sync: a kit path it cannot write is an error, not a silent success" \
	failed_write_is_an_error
run_case "sync: hand-owned paths are untouched" \
	hand_owned_untouched

run_case "check: passes on a freshly generated kit" \
	check_passes_when_fresh
run_case "check: fails and names a hand-edited generated file" \
	check_detects append .claude/rules/plain.md
run_case "check: fails and names a hand-edited ROLE.md" \
	check_detects append ROLE.md
run_case "check: fails and names an extra file in an owned subtree" \
	check_detects extra .claude/agents/extra.md
run_case "check: fails and names an extra symlink in an owned subtree" \
	check_detects symlink .claude/agents/stray.md
run_case "check: fails and names a missing file in an owned subtree" \
	check_detects remove .claude/rules/plain.md
run_case "check: fails and names a missing owned subtree" \
	check_detects remove .claude/skills
run_case "check: fails and names a hand-edited Codex agent TOML" \
	check_detects_codex append .codex/agents/jarvis-alpha.toml
run_case "check: fails and names a hand-edited Codex AGENTS.md" \
	check_detects_codex append .codex/AGENTS.md
run_case "check: fails and names an extra file in the Codex skills" \
	check_detects_codex extra .agents/skills/extra.md
run_case "check: fails and names a missing Codex rule" \
	check_detects_codex remove .jarvis/rules/plain.md
run_case "check: passes when only hand-owned files differ" \
	check_ignores_hand_owned
run_case "check: does not modify the kit and leaves no temp directory behind" \
	check_is_read_only

run_case "determinism: identical output under LC_ALL=C and LC_ALL=en_US.UTF-8" \
	same_output_across_locales

printf '\n%d passed, %d failed\n' "$pass" "$fail"
[[ $fail -eq 0 && $pass -gt 0 ]]
